name: Test

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - name: npm install, build, and test
         run: |
          npm install axios
       - uses: actions/checkout@v2
       - uses: ./
        #with:
          #GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          #TENOR_TOKEN: ${{secrets.TENOR_TOKEN}}